### ISSUE TITLE
Convert all argparse arguments to data classes + simple parsing

### ISSUE THREAD

**Issue by luke-carlson** [apple/ml-mdm#46]
https://pypi.org/project/simple-parsing/

**Comment by brokoli777** [comment]
Hi! I would like to work on this issue. I am looking into where argparse is being used and found the following files:
- ml_mdm\clis\download_tar_from_index.py
- ml_mdm\clis\run_torchmetrics.py

I saw some other files were already using simple parser, so I will try to do it similar to them.

**Comment by luke-carlson** [comment]
Thank you, that would be great! Here are the simple parsing docs https://github.com/lebrice/SimpleParsing

**Comment by brokoli777** [comment]
I made the pull request, could you please take a look at it and let me know if there are any changes are to be made?

**Comment by luke-carlson** [comment]
Thank you, in general https://github.com/apple/ml-mdm/blob/main/ml_mdm/config.py also uses argparse

**Comment by brokoli777** [comment]
Understood, I will update the pull request to modify that as well.
